### ISSUE TITLE
[Feature Request] Extra Options

### ISSUE THREAD

**Issue by ssj71** [cth103/plugin-torture#1]
Someone on IRC pointed me to this. Its already been helpful to debug some of my plugins. There are a few things I noticed:
1. The readme doesn't list the -i option to select the index of ladspa plugins in a pack. I couldn't get the useage to pop up (tried -h, --help, both said unknown argument). Anyhow, please update the readme.
2. LV2 plugins also can come in a pack I don't have any experience with lilv, but would it be difficult to add an option to specify the plugin URI within the manifest.ttl?
3. This one's tougher, but would it be possible to change the settings through program arguments? My plugins are fine under default settings, but I'm suspicious some settings might have problems.

Thanks for a great program.

**Comment by cth103** [comment]
Hi there
1.  That's fixed now in git.
2. I think the easiest way to do what you want is to specify the plugin's individual .ttl file rather than the manifest.ttl; does that do what you are after?
3. Code to do that was already there; I've updated the README to describe how you can set up plugin inputs before the torture.  Let me know if that doesn't do what you need.

Best
Carl

**Comment by cth103** [comment]
I'm going to mark this as closed as I think everything is ok; leave a comment if not!  Thanks!
